### ISSUE TITLE
Please share traind models

### ISSUE THREAD

**Issue by karim23657** [MahtaFetrat/ManaTTS-Persian-Speech-Dataset#1]
Hello @MahtaFetrat ,Thank you for your great dataset.

**Comment by MahtaFetrat** [comment]
Hello @karim23657,
I’m glad you found the dataset useful, and thank you for including it in your valuable project, [awesome-Persian-Speech](https://github.com/karim23657/awesome-Persian-Speech)—I really appreciate it.
As for the model, we are still working on it, and unfortunately, it’s not ready for release at this time.

Best regards,
Mahta Fetrat
